### PR TITLE
Rails 7.0 support

### PR DESCRIPTION
**Pull request by attack**
Update gemspec to allow Rails 7.0.x.
Update workflow matrix to test against Rails 7.0
Update base Gemfile to use Rails 7.0.1.
Update specs to match [call signature for transaction](https://github.com/rails/rails/blob/v7.0.1/activerecord/lib/active_record/transactions.rb#L208)

### CODE REVIEW

**Comment by grosser** [comment]
should add ruby 3 too ?

**Comment by grosser** [comment]
CI complains about mimemagic so that will need an update too, maybe in it's own clean PR ?

**Comment by attack** [comment]
> should add ruby 3 too ?

Yeah, no problem

> CI complains about mimemagic so that will need an update too, maybe in it's own clean PR ?

Yes, I will add a preceding PR for mimemagic. Many of the versions were yanked due to licensing.

**Comment by attack** [comment]
Mimemagic fix in #33

**Comment by attack** [comment]
Updated;
- rebased mimemagic fix #33 
- support Ruby 3.0 in tests for Rails 6.0, 6.1 and 7.0 (Rails 5.2 didn't pass out of the box using Ruby 3.0.3 locally for me, so I didn't include it)

I required the bump of sqlite3 with Ruby 3.0.3 for local development on M1.

**Comment by grosser** [comment]
rebase ftw

**Comment by grosser** [comment]
0.8.0 thanks!

**Pull request merged**
