### PR TITLE
Support Rails 6

### PR DESCRIPTION
**Pull request by chamnap**
Specs are running fine with rails 6.

### CODE REVIEW

**Comment by grosser** [comment]
this library was supposed to die with rails 3 🤷‍♂ 
if you have some time, this could use a re-write to use actual `after_commit` hooks instead
I'll try fixing testing here first https://github.com/grosser/ar_after_transaction/pull/23

**Comment by grosser** [comment]
please rebase 🎉

**Comment by chamnap** [comment]
Done :)

**Comment by grosser** [comment]
0.6.0 🎉

**Pull request merged**
