### PR TITLE
Small tweaks

### PR DESCRIPTION
**Pull request by vladimirtemnikov**

### CODE REVIEW

**Comment by grosser** [comment]
I removed reek/rubocop because they were not working and not running in CI
... already did the pry cleanup/ruby-version-bump ... so maybe just close this (or make a new clean rubocop PR if you care, but maybe just leave it be :D )

**Comment by grosser** [comment]
nvm ... this has some nice cleanup, 1 more rebase plz

**Comment by vladimirtemnikov** [comment]
Ok then :)

**Comment by vladimirtemnikov** [comment]
Done here

**Pull request merged**
